#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Manifest + config contract gate.

Part 1: configs/ == docs/experiment_protocol.md.
  configs/*.yaml are a derived VIEW of the protocol, produced by projects/ca_tosg/utils/configs.py.
  This gate regenerates all five from the protocol and byte-compares them with the committed files,
  so the two can never drift: edit the protocol without regenerating (or hand-edit a config) and
  this FAILS. The protocol stays the single normative source; configs never become a second one.

Part 2: the frozen manifests' INTERNAL relative paths.
  ONE rule, stated once and enforced here: every path inside a manifest is relative to the
  REPOSITORY ROOT (it used to be relative to paper1/). The gate resolves each of them and
  recomputes each recorded md5/sha256 from the file it lands on. A manifest whose pins point at
  nothing -- or at something whose hash has moved on -- is a decorative manifest, so this fails
  loudly rather than skipping. The migration itself is docs/restructure/migrate_manifests.py.

Exit 0 iff every check passes.

  python tests/test_manifest.py
"""
import hashlib
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'projects/ca_tosg/utils'))

import configs  # noqa: E402

CONFIG_DIR = os.path.join(ROOT, 'configs')
MANIFESTS = ['results/manifests/FROZEN_MANIFEST.json', 'results/manifests/P4A_MANIFEST.json']
PATH_KEYS = ('file', 'model')


def check_configs():
    """Every configs/*.yaml must be exactly what the protocol generates today."""
    want = configs.build()
    fails = []
    for name, body in sorted(want.items()):
        p = os.path.join(CONFIG_DIR, name)
        if not os.path.exists(p):
            fails.append('configs/%s MISSING (run: python projects/ca_tosg/utils/configs.py --write)'
                         % name)
            continue
        have = open(p, encoding='utf-8').read()
        if have != body:
            n = sum(1 for a, b in zip(have.splitlines(), body.splitlines()) if a != b)
            fails.append('configs/%s DRIFT vs docs/experiment_protocol.md (%d differing lines, '
                         '%d vs %d bytes)' % (name, n, len(have), len(body)))
        else:
            print('  configs/%-22s == protocol-derived (%d bytes)' % (name, len(body)))

    extra = sorted(f for f in os.listdir(CONFIG_DIR)
                   if f.endswith('.yaml') and f not in want) if os.path.isdir(CONFIG_DIR) else []
    for f in extra:
        fails.append('configs/%s is not generated by configs.py -- an ungoverned second source' % f)
    return fails


def _hash(p, algo):
    h = hashlib.new(algo)
    h.update(open(p, 'rb').read())
    return h.hexdigest()


def _walk(obj, path, fails, stats):
    if isinstance(obj, dict):
        rel = next((obj[k] for k in PATH_KEYS if isinstance(obj.get(k), str)), None)
        if rel is not None:
            if os.path.isabs(rel):
                fails.append('%s: absolute path in a manifest (%s) -- must be repo-root relative'
                             % (path, rel))
            p = os.path.normpath(os.path.join(ROOT, rel))
            if not os.path.exists(p):
                fails.append('%s: relpath does not resolve from the repo root -> %s' % (path, rel))
            else:
                stats['resolved'] += 1
                for algo in ('md5', 'sha256'):
                    if algo in obj:
                        got = _hash(p, algo)
                        stats['hashed'] += 1
                        if got != obj[algo]:
                            fails.append('%s: %s mismatch for %s (manifest %s..., file %s...)'
                                         % (path, algo, rel, obj[algo][:12], got[:12]))
        for k, v in obj.items():
            _walk(v, path + '/' + str(k), fails, stats)
    elif isinstance(obj, list):
        for i, v in enumerate(obj):
            _walk(v, path + '[%d]' % i, fails, stats)


def check_manifests():
    fails = []
    for rel in MANIFESTS:
        p = os.path.join(ROOT, rel)
        if not os.path.exists(p):
            fails.append('%s MISSING' % rel)
            continue
        stats = {'resolved': 0, 'hashed': 0}
        _walk(json.load(open(p)), rel, fails, stats)
        print('  %-40s %d relpath(s) resolve, %d recorded hash(es) re-verified'
              % (rel, stats['resolved'], stats['hashed']))
        if stats['resolved'] == 0:
            fails.append('%s: no resolvable path at all -- the gate would pass vacuously' % rel)
    return fails


def main():
    print('configs == protocol:')
    fails = check_configs()
    print('manifest relpaths (repo-root relative) + recorded hashes:')
    fails += check_manifests()
    if fails:
        print('\nMANIFEST/CONFIG GATE FAIL:')
        for f in fails:
            print('  ' + f)
        return 1
    print('MANIFEST/CONFIG GATE PASS: %d configs match the protocol; %d manifests resolve.'
          % (len(configs.build()), len(MANIFESTS)))
    return 0


if __name__ == '__main__':
    sys.exit(main())
