#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Gate (R31-4): the paper compiles, with zero errors and inside the page limit.

Everything else in this suite checks what the source *says*; nothing checked that it *builds*, or
how long it is. A page limit that is only ever measured by a human is a limit nobody enforces.

Engine: `tectonic` (self-contained, no root, no system texlive). The conda `texlive-core` build in
this environment cannot generate its own formats -- `mktexfmt` looks for a Perl module that ships as
a shell script -- so tectonic is what the gate uses, and it is pinned to the same env.

PASS requires: the build returns 0, the log contains no LaTeX error, and the page count is within
`MAX_PAGES`. Overfull \\hbox warnings are counted and reported per page (a column that runs over the
margin is a layout fault, not a typographic nicety), but they do not fail the build.

    python tests/test_compile.py [--report]
"""
from __future__ import annotations

import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAPER = os.path.join(ROOT, 'paper')
TEX = os.path.join(PAPER, 'main.tex')
LOG = os.path.join(PAPER, 'main.log')
DOCS = ('main', 'supplementary')          # R40: both delivered documents are built and checked
REPORT = os.path.join(ROOT, 'docs', 'compile_report.md')
TECTONIC = os.path.expanduser('~/miniconda3/envs/latex/bin/tectonic')
MAX_PAGES = 17


def compile_one(name):
    return subprocess.run([TECTONIC, '-X', 'compile', f'{name}.tex', '--keep-logs', '--print'],
                          cwd=PAPER, capture_output=True, text=True, timeout=1800)


def compile_paper():
    if not os.path.exists(TECTONIC):
        return None, f'tectonic not found at {TECTONIC}'
    return {n: compile_one(n) for n in DOCS}, None


def parse_one(name):
    """(pages, errors, overfull, undefined) for one document."""
    log = os.path.join(PAPER, f'{name}.log')
    if not os.path.exists(log):
        return None, 1, [], ['no log']
    text = open(log, encoding='utf-8', errors='replace').read()
    m = re.search(r'Output written on \S+ \((\d+) pages', text)
    pages = int(m.group(1)) if m else None
    errors = re.findall(r'^! .*$', text, re.M)
    overfull = re.findall(r'Overfull \\hbox \(([\d.]+)pt too wide\)[^\n]*', text)
    undef = [l.strip() for l in text.split('\n')
             if ('undefined' in l and ('Reference' in l or 'Citation' in l))]
    # R40: the reader-visible symptom is a "??" in the RENDERED text, so extract it rather than
    # grepping the compressed byte stream -- the first attempt did the latter and false-positived on
    # both documents, because arbitrary bytes contain '??'.
    pdf = os.path.join(PAPER, f'{name}.pdf')
    if os.path.exists(pdf):
        try:
            import pypdf
            text = '\n'.join((pg.extract_text() or '') for pg in pypdf.PdfReader(pdf).pages)
            hits = [ln.strip() for ln in text.split('\n') if '??' in ln]
            for h in hits[:3]:
                undef.append(f'rendered "??" in {name}.pdf: {h[:80]}')
        except Exception as exc:                      # extraction is best-effort, never a false PASS
            undef.append(f'{name}.pdf text extraction failed: {exc}')
    return pages, len(errors), overfull, undef


def parse_log():
    if not os.path.exists(LOG):
        return None, 0, []
    text = open(LOG, encoding='utf-8', errors='replace').read()
    m = re.search(r'Output written on \S+ \((\d+) pages', text)
    pages = int(m.group(1)) if m else None
    errors = re.findall(r'^! .*$', text, re.M)
    overfull = re.findall(r'Overfull \\hbox \(([\d.]+)pt too wide\)[^\n]*', text)
    return pages, len(errors), overfull


def main():
    runs, err = compile_paper()
    if err:
        print(f'COMPILE GATE FAIL: {err}')
        return 1
    stats = {n: parse_one(n) for n in DOCS}
    pages, n_err, overfull, undef = stats['main']
    ok_build = all(r.returncode == 0 for r in runs.values())
    ok_pages = pages is not None and pages <= MAX_PAGES
    all_err = sum(stats[n][1] for n in DOCS)
    all_undef = [f'{n}: {u}' for n in DOCS for u in stats[n][3]]
    for n in DOCS:
        p_, e_, o_, u_ = stats[n]
        print(f'compile[{n}]: returncode={runs[n].returncode}, LaTeX errors={e_}, pages={p_}, '
              f'overfull hbox={len(o_)}, undefined refs/cites={len(u_)}')
    if '--report' in sys.argv or True:
        with open(REPORT, 'w', encoding='utf-8') as f:
            f.write('# Compile report\n\nGenerated by `python tests/test_compile.py` '
                    '(engine: tectonic).\n\n')
            f.write('| document | pages | errors | undefined | overfull |\n|---|---|---|---|---|\n')
            for n in DOCS:
                p_, e_, o_, u_ = stats[n]
                f.write(f'| {n} | {p_} | {e_} | {len(u_)} | {len(o_)} |\n')
            f.write(f'\nPage limit (main): {MAX_PAGES}.\n\n')
            if overfull:
                f.write('## Overfull boxes (pt too wide)\n\n')
                for o in overfull:
                    f.write(f'- {o}pt\n')
            else:
                f.write('No overfull boxes.\n')
    if not ok_build or all_err or not ok_pages or all_undef:
        why = []
        if not ok_build:
            why.append('a build returned non-zero')
        if all_err:
            why.append(f'{all_err} LaTeX error(s)')
        if not ok_pages:
            why.append(f'{pages} pages > {MAX_PAGES}')
        if all_undef:
            why.append(f'{len(all_undef)} undefined reference/citation: ' + '; '.join(all_undef[:3]))
        print('COMPILE GATE FAIL: ' + '; '.join(why))
        return 1
    print(f'COMPILE GATE PASS: main {pages} pages, supplementary {stats["supplementary"][0]} pages, '
          f'0 errors, 0 undefined references, {len(overfull)} overfull hbox in main.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
