#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Manifest + config contract gate.

Part 1 (this commit): configs/ == docs/experiment_protocol.md.
  configs/*.yaml are a derived VIEW of the protocol, produced by projects/ca_tosg/utils/configs.py.
  This gate regenerates all five from the protocol and byte-compares them with the committed files,
  so the two can never drift: edit the protocol without regenerating (or hand-edit a config) and
  this FAILS. The protocol stays the single normative source; configs never become a second one.

Part 2 arrives with the manifest relpath migration (commit 3/4).

Exit 0 iff every check passes.

  python tests/test_manifest.py
"""
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'projects/ca_tosg/utils'))

import configs  # noqa: E402

CONFIG_DIR = os.path.join(ROOT, 'configs')


def check_configs():
    """Every configs/*.yaml must be exactly what the protocol generates today."""
    want = configs.build()
    fails = []
    for name, body in sorted(want.items()):
        p = os.path.join(CONFIG_DIR, name)
        if not os.path.exists(p):
            fails.append('configs/%s MISSING (run: python projects/ca_tosg/utils/configs.py --write)'
                         % name)
            continue
        have = open(p, encoding='utf-8').read()
        if have != body:
            n = sum(1 for a, b in zip(have.splitlines(), body.splitlines()) if a != b)
            fails.append('configs/%s DRIFT vs docs/experiment_protocol.md (%d differing lines, '
                         '%d vs %d bytes)' % (name, n, len(have), len(body)))
        else:
            print('  configs/%-22s == protocol-derived (%d bytes)' % (name, len(body)))

    extra = sorted(f for f in os.listdir(CONFIG_DIR)
                   if f.endswith('.yaml') and f not in want) if os.path.isdir(CONFIG_DIR) else []
    for f in extra:
        fails.append('configs/%s is not generated by configs.py -- an ungoverned second source' % f)
    return fails


def main():
    print('configs == protocol:')
    fails = check_configs()
    if fails:
        print('\nMANIFEST/CONFIG GATE FAIL:')
        for f in fails:
            print('  ' + f)
        return 1
    print('MANIFEST/CONFIG GATE PASS: %d configs match the protocol.' % len(configs.build()))
    return 0


if __name__ == '__main__':
    sys.exit(main())
