#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Gate (R31-4): the paper compiles, with zero errors and inside the page limit.

Everything else in this suite checks what the source *says*; nothing checked that it *builds*, or
how long it is. A page limit that is only ever measured by a human is a limit nobody enforces.

Engine: `tectonic` (self-contained, no root, no system texlive). The conda `texlive-core` build in
this environment cannot generate its own formats -- `mktexfmt` looks for a Perl module that ships as
a shell script -- so tectonic is what the gate uses, and it is pinned to the same env.

PASS requires: the build returns 0, the log contains no LaTeX error, and the page count is within
`MAX_PAGES`. Overfull \\hbox warnings are counted and reported per page (a column that runs over the
margin is a layout fault, not a typographic nicety), but they do not fail the build.

    python tests/test_compile.py [--report]
"""
from __future__ import annotations

import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAPER = os.path.join(ROOT, 'paper')
TEX = os.path.join(PAPER, 'main.tex')
LOG = os.path.join(PAPER, 'main.log')
REPORT = os.path.join(ROOT, 'docs', 'compile_report.md')
TECTONIC = os.path.expanduser('~/miniconda3/envs/latex/bin/tectonic')
MAX_PAGES = 17


def compile_paper():
    if not os.path.exists(TECTONIC):
        return None, f'tectonic not found at {TECTONIC}'
    r = subprocess.run([TECTONIC, '-X', 'compile', 'main.tex', '--keep-logs', '--print'],
                       cwd=PAPER, capture_output=True, text=True, timeout=1800)
    return r, None


def parse_log():
    if not os.path.exists(LOG):
        return None, 0, []
    text = open(LOG, encoding='utf-8', errors='replace').read()
    m = re.search(r'Output written on \S+ \((\d+) pages', text)
    pages = int(m.group(1)) if m else None
    errors = re.findall(r'^! .*$', text, re.M)
    overfull = re.findall(r'Overfull \\hbox \(([\d.]+)pt too wide\)[^\n]*', text)
    return pages, len(errors), overfull


def main():
    r, err = compile_paper()
    if err:
        print(f'COMPILE GATE FAIL: {err}')
        return 1
    pages, n_err, overfull = parse_log()
    ok_build = r.returncode == 0
    ok_pages = pages is not None and pages <= MAX_PAGES
    print(f'compile: returncode={r.returncode}, LaTeX errors={n_err}, pages={pages} '
          f'(limit {MAX_PAGES}), overfull hbox={len(overfull)}')
    if '--report' in sys.argv or True:
        with open(REPORT, 'w', encoding='utf-8') as f:
            f.write('# Compile report\n\nGenerated by `python tests/test_compile.py` '
                    '(engine: tectonic).\n\n')
            f.write(f'| field | value |\n|---|---|\n| return code | {r.returncode} |\n'
                    f'| LaTeX errors | {n_err} |\n| pages | {pages} |\n'
                    f'| page limit | {MAX_PAGES} |\n| overfull \\\\hbox | {len(overfull)} |\n\n')
            if overfull:
                f.write('## Overfull boxes (pt too wide)\n\n')
                for o in overfull:
                    f.write(f'- {o}pt\n')
            else:
                f.write('No overfull boxes.\n')
    if not ok_build or n_err or not ok_pages:
        why = []
        if not ok_build:
            why.append(f'build returned {r.returncode}')
        if n_err:
            why.append(f'{n_err} LaTeX error(s)')
        if not ok_pages:
            why.append(f'{pages} pages > {MAX_PAGES}')
        print('COMPILE GATE FAIL: ' + '; '.join(why))
        return 1
    print(f'COMPILE GATE PASS: builds clean at {pages} pages '
          f'({len(overfull)} overfull hbox warnings).')
    return 0


if __name__ == '__main__':
    sys.exit(main())
