#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""P2-R14 A-2 — the sentence P1's Limitations needs about its empirical zeros.

**Nothing in P1 is changed by this file.** It drafts the sentence and derives every number in it from
P1's own artefacts. Inserting it into `paper/main.tex` is a P1-branch edit and is left for an explicit
instruction: this line of work is on `p2-perception-first` and does not reach across.

No P1 experiment is re-run and no P1 result is altered. The addition is a statement about what the
existing measurement can and cannot support.

    python p1_limitations_addendum.py [--check]
"""
from __future__ import annotations
import argparse, hashlib, json, os, sys

import numpy as np
import pandas as pd

HERE = os.path.dirname(os.path.abspath(__file__))
P2 = os.path.dirname(HERE)
ROOT = os.path.dirname(os.path.dirname(P2))
BLER = os.path.join(ROOT, 'results', 'channel', 'bler_sionna.csv')
GRID = os.path.join(ROOT, 'results', 'v2', 'v2_grid_validate_ideal.csv')
CHAIN = os.path.join(ROOT, 'results', 'v2', 'payload_chain.json')
FILL_EVAL = os.path.join(HERE, 'awgn_fill_eval.json')
OUT_JSON = os.path.join(HERE, 'p1_limitations_addendum.json')
OUT_MD = os.path.join(HERE, 'p1_limitations_addendum.md')

sys.path.insert(0, HERE)
from awgn_fill import cp_upper                                          # noqa: E402


def sha(p):
    return hashlib.sha256(open(p, 'rb').read()).hexdigest()


def build():
    n_cw_F = json.load(open(CHAIN))['F']['n_cw']
    bl = pd.read_csv(BLER); bl = bl[bl.qam == 16]
    g = pd.read_csv(GRID, usecols=['snr_db', 'channel', 'p_cw'])
    key = {(r.channel, float(r.esno_db)): (int(r.n_err), int(r.n_cw)) for r in bl.itertuples()}

    # Which AWGN cells does the grid carry as p_cw = 0, and where did each of them come from?
    zero_cells = []
    for s in sorted(g[g.channel == 'awgn'].snr_db.unique()):
        p = float(g[(g.channel == 'awgn') & (g.snr_db == s)].p_cw.iloc[0])
        if p != 0.0:
            continue
        hit = key.get(('awgn', float(s)))
        zero_cells.append({'snr_db': int(s), 'sampled': hit is not None,
                           'n_err': hit[0] if hit else None, 'n_cw': hit[1] if hit else None,
                           'upper95': cp_upper(*hit) if hit else None})
    measured = [c for c in zero_cells if c['sampled']]
    inherited = [c for c in zero_cells if not c['sampled']]
    if not measured:
        raise SystemExit('no measured zero-error AWGN cell found -- the premise of this note is gone')
    ns = sorted({c['n_cw'] for c in measured})
    if len(ns) != 1:
        raise SystemExit(f'the measured zero-error cells do not share one sample size: {ns}')
    N = ns[0]
    upper = cp_upper(0, N)

    # What that bound permits, in each of the two accountings
    q_F_worst = float((1.0 - upper) ** n_cw_F)
    cross = json.load(open(FILL_EVAL))['break_even']
    q_star = cross['q_F_at_break_even']
    lost_cw_worst = upper * n_cw_F

    return {'schema': 'catosg-p2-p1-limitations-addendum/1',
            'status': 'DRAFT SENTENCE. Not inserted into paper/main.tex. P1 is on another branch and '
                      'no P1 experiment is touched',
            'inputs': {'bler': sha(BLER), 'grid': sha(GRID), 'fill_eval': sha(FILL_EVAL)},
            'zero_cells': zero_cells,
            'measured_zero_cells_db': [c['snr_db'] for c in measured],
            'inherited_zero_cells_db': [c['snr_db'] for c in inherited],
            'sample_size': int(N), 'upper95': upper, 'n_cw_F': int(n_cw_F),
            'message_accounting': {'q_F_lower_bound': q_F_worst, 'q_F_needed_to_beat_L': q_star,
                                   'undetermined': bool(q_F_worst < q_star)},
            'partial_recovery': {'expected_lost_codewords_upper_bound': lost_cw_worst,
                                 'as_fraction_of_message': lost_cw_worst / n_cw_F},
            'brief_correction': 'the brief described AWGN 10-20 dB as empirical zeros of 0/100,000. '
                                'That holds for %s dB; %s dB were never sampled by the channel table '
                                'and carry zero by P1 §9.3 interpolation between neighbours. The two '
                                'are different kinds of claim and the sentence separates them'
                                % (', '.join(str(c['snr_db']) for c in measured),
                                   ', '.join(str(c['snr_db']) for c in inherited)),
            'command': 'python projects/ca_tosg_p2/protocol/p1_limitations_addendum.py'}


def markdown(m):
    meas = ', '.join(f"{d} dB" for d in m['measured_zero_cells_db'])
    inh = ', '.join(f"{d} dB" for d in m['inherited_zero_cells_db'])
    ma, pr = m['message_accounting'], m['partial_recovery']
    L = ['<!-- GENERATED by projects/ca_tosg_p2/protocol/p1_limitations_addendum.py -- do not edit by hand -->',
         "# A sentence for P1's Limitations (P2-R14 A-2)", '',
         f"**{m['status']}.**", '',
         '## The correction to the brief', '',
         f"{m['brief_correction']}.", '', '| AWGN cell | p_cw in the grid | where it comes from |',
         '|---:|---:|---|']
    for c in m['zero_cells']:
        src = (f"measured: {c['n_err']}/{c['n_cw']:,} codewords" if c['sampled']
               else '**never sampled** — P1 §9.3 interpolation between neighbours')
        L.append(f"| {c['snr_db']} dB | 0 | {src} |")
    L += ['', '## The numbers the sentence rests on', '',
          f"* The measured zero-error cells each drew **{m['sample_size']:,} codewords** and saw none "
          f"in error. The one-sided 95 % upper limit is **{m['upper95']:.3g}** "
          f"(`1 - 0.05^(1/N)`, whose first-order approximation is 3/N).",
          f"* **Message accounting.** With {m['n_cw_F']:,} codewords per F message, a per-codeword loss "
          f"at that upper limit gives q_F as low as **{ma['q_F_lower_bound']:.3f}**. F overtakes L only "
          f"above q_F = {ma['q_F_needed_to_beat_L']:.4f}, so the bound "
          + ('**does not settle** which of F and L is better in that range.'
             if ma['undetermined'] else 'still settles the comparison.'),
          f"* **Partial recovery.** The same bound costs at most "
          f"{pr['expected_lost_codewords_upper_bound']:.2f} codewords of the {m['n_cw_F']:,} in a "
          f"message — {pr['as_fraction_of_message'] * 100:.4f} % of the payload — so under that "
          'accounting the difference between the empirical zero and its upper bound is immaterial.',
          '', '## Draft sentence', '',
          'Ready to paste into the Limitations subsection. It has **not** been inserted.', '',
          '```latex',
          '% Limitations -- addition drafted in P2-R14 A-2; no P1 experiment is affected.',
          f"The AWGN codeword error rates at {meas} are empirical zeros: no error was observed in",
          f"{m['sample_size']:,} codewords at each point, which bounds the rate at "
          f"{m['upper95']:.2g} with 95\\,\\%",
          f"confidence rather than establishing it as zero, and the {inh} cells are interpolated between",
          'neighbouring points and carry no sample of their own. The channel grid consumes all of these',
          'as exact zeros. Under the fragment-aware partial-recovery accounting used here the',
          f"consequence is immaterial, since the bound permits at most "
          f"{pr['expected_lost_codewords_upper_bound']:.2f} lost codewords",
          f"of {m['n_cw_F']:,}. Under an all-or-nothing message accounting it is not immaterial: the same",
          f"bound admits a whole-message success probability as low as {ma['q_F_lower_bound']:.2f}, so the",
          'ordering of the feature-level and object-level actions in that SNR range is not determined',
          'by this measurement.',
          '```', '',
          '## Where it goes, and who inserts it', '',
          "P1's manuscript lives on `p1-phy-rebuild`; this work is on `p2-perception-first`. Editing",
          'across branches from here would be a scope change made without being asked for, so the',
          'sentence is drafted and left. It needs one instruction to apply, and applying it changes no',
          'number in P1 — it constrains what the existing numbers are allowed to claim.', '',
          '## Inputs', '', '| file | sha256 |', '|---|---|']
    for k, v in m['inputs'].items():
        L.append(f"| {k} | `{v[:16]}…` |")
    return '\n'.join(L) + '\n'


def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    m = build()
    js, md = json.dumps(m, indent=1) + '\n', markdown(m)
    if a.check:
        ok = (os.path.exists(OUT_JSON) and open(OUT_JSON).read() == js
              and os.path.exists(OUT_MD) and open(OUT_MD).read() == md)
        print('p1 limitations addendum:', 'reproduced' if ok else 'FAIL -- not what the generator writes')
        return 0 if ok else 1
    open(OUT_JSON, 'w').write(js); open(OUT_MD, 'w').write(md)
    print(md)
    return 0


if __name__ == '__main__':
    sys.exit(main())
