#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""R31-3: rebuild `results/provenance/r9_result_claims.md` from the current replay.

That file is the AUTHORITY for the R9 sentence's allowed wording -- `docs/claims.md` points at it --
and it was still entirely pre-corrigendum: dF -0.0028, payload 0.095 vs 0.217, reduction 56.3%,
Culver -0.0099. A locked-wording file that locks retired numbers is worse than none, because every
downstream check defers to it.

Every number below is read at build time from `results/main/replay_summary.csv` and
`results/main/tau_feasible.csv`; the wording template is fixed, the numbers are not typed.

    python tools/build_r9_claims.py [--check]
"""
from __future__ import annotations

import argparse
import os
import sys

import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'results/provenance/r9_result_claims.md')
REPLAY = os.path.join(ROOT, 'results/main/replay_summary.csv')
FEASIBLE = os.path.join(ROOT, 'results/main/tau_feasible.csv')
DELTA = 0.005


def build() -> str:
    r = pd.read_csv(REPLAY)
    f = pd.read_csv(FEASIBLE)
    p = r[(r.split == 'test') & (r.budget.round(2) == 0.20)].iloc[0]
    pf = f[(f.split == 'test') & (f.budget.round(2) == 0.20)].iloc[0]
    L = []
    w = L.append
    w('# R9 RF-vs-threshold result --- LOCKED claim wording (P2-B)')
    w('')
    w('**Generated by `python tools/build_r9_claims.py` from `results/main/replay_summary.csv` and')
    w('`results/main/tau_feasible.csv`. Do not edit by hand.** This file is the authority for the R9')
    w('sentence\'s allowed wording; `docs/claims.md` is auto-generated from `main.tex` and points here.')
    w(f'Metric = frame-level realised F1 / channel-use payload. Margin $\\delta$ = {DELTA} (PROTOCOL R9);')
    w('paired bootstrap, 10,000 resamples, percentile, on the frozen 200-realisation draw.')
    w('')
    w('## PRIMARY --- test @ B_max = 0.20, against the NOMINAL threshold (the sole confirmatory comparison)')
    w('')
    w('| Field | Value |')
    w('|---|---|')
    w(f'| dF = F1_RF - F1_tau | {p.dF_mean:+.5f} (mean); 95% CI = [{p.dF_lcb95:+.5f}, {p.dF_ucb95:+.5f}] |')
    w(f'| Non-inferiority | LCB95(dF) = {p.dF_lcb95:+.5f} > -delta (= -{DELTA}) -> **non-inferior** |')
    w(f'| Payload | B_RF = {p.B_RF:.5f} vs B_tau = {p.B_tau:.5f} Msym; reduction '
      f'**{100 * p.payload_reduction:.1f}%**; UCB95(dB) = {p.dB_ucb95:+.5f} < 0 |')
    w(f'| Comparator budget | the nominal threshold is itself OVER budget: {p.B_tau:.4f} > 0.20 Msym |')
    w('| Verdict | non-inferior within the pre-registered margin AND communication-superior |')
    w('')
    w('**Allowed wording (verbatim, locked):**')
    w('')
    w(f'> The selector\'s F1 is lower than the nominal threshold rule\'s by {abs(p.dF_mean):.5f} '
      f'(95% CI [{p.dF_lcb95:+.5f}, {p.dF_ucb95:+.5f}], entirely below zero) yet far within the')
    w(f'> pre-registered non-inferiority margin of {DELTA}, while reducing communication payload by '
      f'{100 * p.payload_reduction:.1f}% against a comparator that is itself over budget '
      f'({p.B_tau:.4f} > 0.20 Msym).')
    w('')
    w('**BANNED wording** (misrepresents a small-but-significant F1 loss as no loss): "same F1", "no')
    w('accuracy loss", "matches F1", or any phrasing implying the selector\'s F1 equals or exceeds the')
    w('nominal threshold rule\'s at this cell.')
    w('')
    w('## SECONDARY (CI only --- no non-inferiority decision; multiple-comparison protection, R9e)')
    w('')
    w('| Comparison | dF mean | dF 95% CI | Note |')
    w('|---|---|---|---|')
    w(f'| **test @ B=0.20 vs `tau_feasible`** | {pf.dF_vs_feasible:+.5f} | --- | budget-matched '
      f'({pf.B_tau_feasible:.4f} Msym); payload reduction {100 * pf.payload_reduction_vs_feasible:.1f}%. '
      '**No non-inferiority decision is attached to this comparison** (R31-2) |')
    for split, label in (('culver', 'Culver-City @ B=0.20'), ('test', 'test @ B=0.10'),
                         ('test', 'test @ B=0.30')):
        b = 0.20 if 'Culver' in label else (0.10 if '0.10' in label else 0.30)
        row = r[(r.split == split) & (r.budget.round(2) == round(b, 2))].iloc[0]
        note = ('**exceeds the delta margin** --- reported as an observed CI, not adjudicated'
                if abs(row.dF_lcb95) > DELTA or abs(row.dF_ucb95) > DELTA else
                'secondary --- CI only, not adjudicated')
        if 'Culver' in label:
            w(f'| **{label}** | {row.dF_mean:+.5f} | [{row.dF_lcb95:+.5f}, {row.dF_ucb95:+.5f}] | {note} |')
        else:
            w(f'| {label} | {row.dF_mean:+.5f} | [{row.dF_lcb95:+.5f}, {row.dF_ucb95:+.5f}] | {note} |')
    w('| validate (all budgets) | --- | --- | in-sample reference only, not a generalisation claim |')
    w('')
    w('_Do not aggregate a secondary cell into the primary claim._')
    return '\n'.join(L) + '\n'


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument('--check', action='store_true',
                    help='fail if the committed file is not what the current replay produces')
    a = ap.parse_args()
    content = build()
    if a.check:
        cur = open(OUT, encoding='utf-8').read() if os.path.exists(OUT) else ''
        if cur != content:
            print('R9 WORDING GATE FAIL: results/provenance/r9_result_claims.md does not match the '
                  'current replay. It is the authority for the locked wording, so a stale copy '
                  'silently authorises retired numbers. Re-run: python tools/build_r9_claims.py')
            return 1
        print('R9 WORDING GATE PASS: the locked-wording file matches the current replay.')
        return 0
    open(OUT, 'w', encoding='utf-8').write(content)
    print(f'wrote {OUT} ({content.count(chr(10))} lines) from the current replay')
    return 0


if __name__ == '__main__':
    sys.exit(main())
