#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Build docs/milestone_summary.md — a one-page results summary for milestone delivery.

**Every number is read from the committed product at build time**; none is typed into this file.
The sources are the ones registered in `docs/canonical_quantities.md`, so a change in the data
changes the page and cannot silently disagree with the paper.

Sections: R9 decision conditions, the nine-cell main table, the E-collapse cost in units of the
non-inferiority margin, the FA-1 shape finding, collaborator scale, the SECOND-backbone boundary,
and selector latency.

    python tools/build_milestone_summary.py
"""
from __future__ import annotations

import os
import sys

import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'docs', 'milestone_summary.md')
DELTA = 0.005          # the pre-registered non-inferiority margin, PROTOCOL R9


def csv(rel):
    return pd.read_csv(os.path.join(ROOT, rel))


def main() -> int:
    r9 = csv('results/main/r9_decision.csv')
    rep = csv('results/main/replay_summary.csv')
    fx = csv('results/main/fixed_references.csv')
    miss = csv('results/main/r10c_missed_e_cost.csv')
    fa1 = csv('results/sensitivity/feature_ablation.csv')
    col = csv('results/sensitivity/collaborator_scale.csv')
    p4b = csv('results/p4b/replay_summary.csv')
    lat = csv('results/latency/selector_latency.csv')
    tf = csv('results/main/tau_feasible.csv')
    b_f = float(fx[(fx.split == 'validate') & (fx.policy == 'Fixed-F')].payload_msym.iloc[0])

    L = []
    w = L.append
    w('# CA-TOSG — milestone results summary (draft)')
    w('')
    w('Generated by `python tools/build_milestone_summary.py`. **Every number below is read from a '
      'committed product at build time** — the same sources registered in '
      '`docs/canonical_quantities.md` — so this page cannot drift from the paper or from the data. '
      'Draft for Peiyi to check before it goes to Josh.')
    w('')

    w('## 1. Pre-registered decision (R9)')
    w('')
    w('The confirmatory comparison was fixed before the numbers were seen: frozen selector versus '
      f'the re-tuned SNR threshold, on **test at $B_{{\\max}}=0.20$**, non-inferiority margin '
      f'$\\delta={DELTA}$.')
    w('')
    w('| condition | value | met |')
    w('|---|---|---|')
    for _, r in r9.iterrows():
        w(f'| `{r.condition}` | {r.value:+.5f} | {"**yes**" if r.result else "no"} |')
    w('')
    # R23-7: quote-both-or-neither. The nominal saving is against a threshold that is itself over
    # budget, so it may never appear without the budget-matched one beside it. Both are READ, not
    # typed, and the generator refuses to emit either if tau_feasible.csv cannot supply the second.
    red_nominal = 100 * float(r9[r9.condition.str.contains('B_tau')].value.iloc[-1])
    tfp = tf[(tf.split == 'test') & (tf.budget == 0.20)]
    if len(tfp) != 1:
        raise SystemExit('milestone FUSE: tau_feasible.csv has no test@B0.20 row -- the nominal '
                         'payload saving may not be quoted without the budget-matched one (R23-7)')
    red_feasible = 100 * float(tfp.payload_reduction_vs_feasible.iloc[0])
    over = float(tfp.B_tau_nominal.iloc[0])
    w(f'All {len(r9)} conditions hold: the selector is non-inferior within the margin **and** '
      'strictly cheaper. The payload saving is **two-track and must be quoted as both**: '
      f'**{red_nominal:.1f}%** against the nominal threshold (which is itself over budget at '
      f'{over:.4f} > 0.20 Msym) and **{red_feasible:.1f}%** against the budget-matched '
      '$\\tau_{\\mathrm{feasible}}$.')
    w('')

    w('## 2. Main table — three splits × three budgets')
    w('')
    w('Realised F1 and channel use of the frozen selectors, from the 200-realisation replay. '
      f'"Share of $B_F$" is the payload as a fraction of fixed feature-level transmission '
      f'({b_f} Msym/frame).')
    w('')
    w('| split | $B_{\\max}$ | F1 | payload (Msym) | share of $B_F$ | vs. threshold (F1) |')
    w('|---|---|---|---|---|---|')
    for split in ('validate', 'test', 'culver'):
        for _, r in rep[rep.split == split].sort_values('budget').iterrows():
            w(f'| {split} | {r.budget:.2f} | {r.F1_RF:.5f} | {r.B_RF:.5f} | '
              f'{100 * r.B_RF / b_f:.1f}% | {r.dF_mean:+.5f} '
              f'[{r.dF_lcb95:+.5f}, {r.dF_ucb95:+.5f}] |')
    w('')

    w('## 3. E-collapse — the cost of the action the selector never takes')
    w('')
    w('The deployed selectors essentially never choose the ego-only action $E$. Summing the '
      'clairvoyant-$E$ cells the frozen selector misses gives the F1 cost per frame, expressed '
      f'below in units of the non-inferiority margin $\\delta={DELTA}$.')
    w('')
    w('| split | $B_{\\max}$ | F1 cost / frame | in units of $\\delta$ |')
    w('|---|---|---|---|')
    g = miss.groupby(['split', 'budget']).F1_cost_per_framereal.sum()
    for (split, budget), v in g.items():
        w(f'| {split} | {budget:.2f} | {v:.5f} | {v / DELTA:.2f}$\\delta$ |')
    tst = [v / DELTA for (s, _b), v in g.items() if s == 'test']
    w('')
    w(f'On test the cost is **{min(tst):.2f}--{max(tst):.2f}$\\delta$** — the single largest '
      'identified headroom in the method, and the reason $E$ is reported as a limitation rather '
      'than as a working third action.')
    w('')

    w('## 4. FA-1 — neither half of the input is sufficient')
    w('')
    w('Feature ablation under the frozen protocol. The finding is about the *shape* of the '
      'failure, not about an accuracy gap.')
    w('')
    w('| split | $B_{\\max}$ | variant | features | F1 | payload | $\\rho_F$ |')
    w('|---|---|---|---|---|---|---|')
    for _, r in fa1[fa1.variant.isin(['channel_only', 'task_only', 'combined'])].iterrows():
        w(f'| {r.split} | {r.budget:.2f} | {r.variant} | '
          f'{"" if pd.isna(r.n_features) else int(r.n_features)} | {r.F1:.5f} | '
          f'{r.payload:.5f} | {r.rho_F:.4f} |')
    t3 = fa1[(fa1.split == 'test') & (fa1.budget == 0.3)].set_index('variant')
    co_f1, cb_f1 = float(t3.loc['channel_only', 'F1']), float(t3.loc['combined', 'F1'])
    co_pay, cb_pay = float(t3.loc['channel_only', 'payload']), float(t3.loc['combined', 'payload'])
    ratio = co_pay / cb_pay
    # R23-3: the direction of the F1 comparison is DERIVED, never typed. The retired template said
    # "reaches a higher F1"; under the corrected convention the channel-only variant is lower on
    # BOTH axes, and a hand-written direction word is exactly what went stale.
    dirn = ('a higher F1 than the full selector, but only by spending' if co_f1 > cb_f1 else
            'a LOWER F1 than the full selector while still spending')
    w('')
    w('Channel state alone stops requesting features altogether at the two tighter budgets '
      f'(feature-request rate 0, payload pinned at $B_L$); at $B_{{\\max}}=0.30$ it does reach '
      f'{dirn} **{ratio:.2f}×** the channel use — {co_f1:.5f} against {cb_f1:.5f} F1 '
      f'({co_f1 - cb_f1:+.5f}) at {co_pay:.5f} against {cb_pay:.5f} Msym. Cues '
      'alone never request features at all.')
    w('')

    w('## 5. Collaborator scale')
    w('')
    w('Requested collaborators $N\\in\\{1,2,3\\}$ with the frozen selector, $\\lambda^\\star$ and '
      '$\\tau^\\star$ untouched.')
    w('')
    w('| split | $B_{\\max}$ | N | F1 | payload | $\\Delta$F1 vs $N{=}1$ |')
    w('|---|---|---|---|---|---|')
    ca = col[col.semantics == 'A']
    for _, r in ca.iterrows():
        d = '—' if pd.isna(r.dF_vs_N1_mean) else \
            f'{r.dF_vs_N1_mean:+.5f} [{r.dF_vs_N1_lcb95:+.5f}, {r.dF_vs_N1_ucb95:+.5f}]'
        w(f'| {r.split} | {r.budget:.2f} | {int(r.N)} | {r.F1:.5f} | {r.payload:.5f} | {d} |')
    t = ca[(ca.split == 'test') & (ca.budget == 0.2)].set_index('N')
    w('')
    w(f'Returns diminish sharply: on test at $B_{{\\max}}=0.20$ the second collaborator is worth '
      f'{float(t.loc[2, "dF_vs_N1_mean"]):+.5f} F1 and the third adds only '
      f'{float(t.loc[3, "dF_vs_N1_mean"]) - float(t.loc[2, "dF_vs_N1_mean"]):+.5f} more, for '
      f'{float(t.loc[3, "payload"]) - float(t.loc[2, "payload"]):+.5f} Msym of extra channel use.')
    w('')

    w('## 6. Boundary — a second detection backbone (SECOND)')
    w('')
    w('The same pipeline on a SECOND/VoxelNet backbone, under the equal-budget protocol.')
    w('')
    w('| split | $B_{\\max}$ | F1 | payload | payload reduction | $\\Delta$F1 vs threshold |')
    w('|---|---|---|---|---|---|')
    for _, r in p4b.iterrows():
        w(f'| {r.split} | {r.budget:.2f} | {r.F1_RF:.5f} | {r.B_RF:.5f} | '
          f'{100 * r.payload_reduction:.1f}% | {r.dF_mean:+.5f} '
          f'[{r.dF_lcb95:+.5f}, {r.dF_ucb95:+.5f}] |')
    held = p4b[p4b.split != 'validate']
    w('')
    w(f'In-sample the arm is effective; on the held-out splits every $\\Delta$F1 is negative '
      f'({held.dF_mean.min():+.5f} to {held.dF_mean.max():+.5f}), while the payload reductions '
      f'({100 * held.payload_reduction.min():.0f}--{100 * held.payload_reduction.max():.0f}%) '
      'follow from a collapse to $L$ rather than from good selection. Reported as a **boundary of '
      'the method**, not as generalisation evidence.')
    w('')

    w('## 7. Deployment cost')
    w('')
    w('| model | mean (ms) | std | P95 | trials |')
    w('|---|---|---|---|---|')
    for _, r in lat.iterrows():
        w(f'| {r.model} | {r.mean_ms:.3f} | {r.std_ms:.3f} | {r.p95_ms:.3f} | {int(r.n_trials)} |')
    slow = lat.loc[lat.mean_ms.idxmax()]
    w('')
    w(f'The slowest of the three, `{slow.model}`, runs in {slow.mean_ms:.1f} ± {slow.std_ms:.1f} ms '
      f'per frame (P95 {slow.p95_ms:.1f} ms) on a single CPU core, inside the 100 ms budget of a '
      '10 Hz LiDAR cycle. Mean and P95 are quoted from the same row by construction — the registry '
      'gate refuses a cross-model splice.')
    w('')

    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(L) + '\n')
    print(f'wrote {os.path.relpath(OUT, ROOT)} ({len(L)} lines) — every number read from a '
          'committed product')
    return 0


if __name__ == '__main__':
    sys.exit(main())
