#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""R46-4: gate counts are computed from the registry, never typed.

Three places carried a hand-written count of how many gates exist and how many a clean clone can
run: `tools/verify_results.py`'s usage line ("7 of 9"), `docs/reproducibility.md`'s two-tier
section, and the last row of its six-step table. All three were wrong at the same time, in
different ways, because each was updated by hand when someone remembered. A count that is typed is
a count that goes stale; this reads `verify_results.GATES` and writes the numbers.

`--check` fails when any generated block differs from what the registry produces.

    python tools/build_gate_counts.py [--check]
"""
from __future__ import annotations

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'tools'))

REPRO = os.path.join(ROOT, 'docs', 'reproducibility.md')
VERIFY = os.path.join(ROOT, 'tools', 'verify_results.py')
BEGIN = '<!-- GATE-COUNTS:BEGIN (generated by tools/build_gate_counts.py -- do not edit) -->'
END = '<!-- GATE-COUNTS:END -->'
USAGE_RX = re.compile(r'(only the checks a CLEAN CLONE can run \()\d+ of \d+(\))')


def counts():
    """(total, content-tier names) as the runner ACTUALLY runs them.

    `GATES` is not the whole registry: `stale-fingerprint exit` is run inline by `__main__` and
    printed like the rest, so counting `len(GATES)` gives 17 while the suite reports 18. Counting
    the list and not the runner is how the hand-written numbers went wrong in the first place, so
    the inline gate is added explicitly here and named, not assumed.
    """
    import verify_results as v
    names = [(tier, name) for tier, name, _cmd in v.GATES]
    names.append(('content', 'stale-fingerprint exit'))     # run inline by verify_results.__main__
    content = [n for tier, n in names if tier == 'content']
    return len(names), content


def block():
    total, content = counts()
    names = ', '.join(f'`{n}`' for n in content)
    return (f'{BEGIN}\n'
            f'* **Tier 1 --- committed-content consistency**: `python tools/verify_results.py '
            f'--content-only` runs **{len(content)} of the {total}** gates ({names}); the other '
            f'**{total - len(content)} are skipped and reported as skipped**. No dataset, no GPU, no '
            f'OpenCOOD checkout. What this tier can establish is bounded and worth stating plainly: '
            f'**the committed results are internally consistent, and the documents still say what '
            f'those results say.** It cannot establish that the results are reproducible from raw '
            f'data.\n'
            f'* **Tier 2 --- full run**: `python tools/verify_results.py` runs all **{total}**. '
            f'Additionally requires the sibling `../OpenCOOD/` checkout, the local grids '
            f'`data/p2/p2_grid_*.csv` and the frozen models `data/p2/selector_B0*.pkl`. '
            f'**Independent reproduction from the raw OPV2V data needs all three, and none of them '
            f'is in this repository** --- so a third party can verify the internal chain here and '
            f'must obtain the dataset and re-run steps 1--4 to verify the rest.\n'
            f'{END}')


def step6_line():
    total, _ = counts()
    return f'{total} gate results'


def render(text):
    i, j = text.find(BEGIN), text.find(END)
    if i < 0 or j < 0:
        raise SystemExit('build_gate_counts: the GATE-COUNTS markers are missing from '
                         'docs/reproducibility.md')
    out = text[:i] + block() + text[j + len(END):]
    # the six-step table's last row also carries the count
    out = re.sub(r'\d+ gate results', step6_line(), out)
    return out


def main() -> int:
    check = '--check' in sys.argv
    total, _ = counts()
    repro = open(REPRO, encoding='utf-8').read()
    verify = open(VERIFY, encoding='utf-8').read()
    want_repro = render(repro)
    want_verify = USAGE_RX.sub(lambda m: f'{m.group(1)}{len(counts()[1])} of {total}{m.group(2)}',
                               verify)
    if check:
        stale = [p for p, cur, want in ((REPRO, repro, want_repro), (VERIFY, verify, want_verify))
                 if cur != want]
        if stale:
            print('GATE COUNT CHECK FAIL: ' + ', '.join(os.path.relpath(p, ROOT) for p in stale)
                  + f' disagree(s) with the registry ({len(counts()[1])} content of {total} total)'
                    ' -- re-run: python tools/build_gate_counts.py')
            return 1
        print(f'GATE COUNT CHECK PASS: {len(counts()[1])} content-tier of {total} gates, '
              'stated the same everywhere.')
        return 0
    open(REPRO, 'w', encoding='utf-8').write(want_repro)
    open(VERIFY, 'w', encoding='utf-8').write(want_verify)
    print(f'wrote the gate counts ({len(counts()[1])} content-tier of {total} total)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
