#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""R45-5: keep `docs/HANDOFF.md`'s commit field from going stale by itself.

The header used to carry a hand-typed short hash. It was wrong within one commit of being written,
every time, and a "read this first" file whose first fact is wrong teaches the reader to distrust
the rest. Hand-maintenance is not the fix here: the field has to be generated.

Two things make that workable:

  * the block between the HTML markers below is written by this tool, never by hand;
  * `--check` does NOT require the recorded hash to equal `HEAD` -- that would fail on every commit
    made after regenerating the file, which is precisely how the previous convention died. It
    requires the recorded hash to be an ANCESTOR of the current HEAD on this branch. That fails
    exactly when the file is describing a state the branch has left (a rebase, a reset, a different
    branch), and passes while the file is merely a few commits behind.

    python tools/build_handoff_header.py [--check]
"""
from __future__ import annotations

import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DOC = os.path.join(ROOT, 'docs', 'HANDOFF.md')
BEGIN = '<!-- HANDOFF-HEADER:BEGIN (generated by tools/build_handoff_header.py -- do not edit) -->'
END = '<!-- HANDOFF-HEADER:END -->'


def git(*args):
    return subprocess.run(['git'] + list(args), cwd=ROOT, capture_output=True, text=True)


def block(sha, branch):
    return (f'{BEGIN}\n'
            f'**Branch** `{branch}` · **written at** `{sha}` · **recovery tag** '
            f'`pre-p0-corrigendum` (the pre-correction state; nothing before it is quotable).\n'
            f'The commit above is where this file was last regenerated, not necessarily the tip: '
            f'read the tip with `git ls-remote origin {branch}`, and regenerate this block with '
            f'`python tools/build_handoff_header.py`.\n'
            f'{END}')


def current():
    text = open(DOC, encoding='utf-8').read()
    i, j = text.find(BEGIN), text.find(END)
    if i < 0 or j < 0:
        return text, None, None
    return text, i, j + len(END)


def recorded_sha(text):
    i = text.find('**written at** `')
    if i < 0:
        return None
    return text[i + len('**written at** `'):].split('`')[0].strip()


def main() -> int:
    check = '--check' in sys.argv
    text, i, j = current()
    branch = git('rev-parse', '--abbrev-ref', 'HEAD').stdout.strip() or 'p1-phy-rebuild'
    sha = git('rev-parse', '--short', 'HEAD').stdout.strip()
    if i is None:
        print('HANDOFF HEADER FAIL: the generated block markers are missing from docs/HANDOFF.md')
        return 1
    if check:
        rec = recorded_sha(text)
        if not rec:
            print('HANDOFF HEADER FAIL: no recorded commit in the generated block')
            return 1
        anc = git('merge-base', '--is-ancestor', rec, 'HEAD')
        if anc.returncode != 0:
            print(f'HANDOFF HEADER FAIL: recorded commit {rec} is not an ancestor of HEAD ({sha}) '
                  f'-- the handoff describes a state this branch has left. Re-run: '
                  f'python tools/build_handoff_header.py')
            return 1
        behind = git('rev-list', '--count', f'{rec}..HEAD').stdout.strip()
        print(f'HANDOFF HEADER PASS: recorded commit {rec} is an ancestor of HEAD '
              f'({behind} commit(s) behind).')
        return 0
    open(DOC, 'w', encoding='utf-8').write(text[:i] + block(sha, branch) + text[j:])
    print(f'wrote the HANDOFF header block at {sha} on {branch}')
    return 0


if __name__ == '__main__':
    sys.exit(main())
