#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""V2-R42 B-2 — write every v2 paper number into LaTeX from the closed-out products.

**No number in paper/v2_draft/ is typed by hand.** They are emitted here, into
`paper/v2_draft/tables/generated_numbers.tex` as `\newcommand` macros and into the result tables, and
the manuscript references the macros. The reason is one round old: `sparsity_payload.csv` carried a
column whose provenance was "the accounting in the change-log" -- arithmetic done in prose, which no
script could re-derive. A number no script can regenerate is a NOTE, not a RESULT.

Sources, all post-close-out:
  results/v2/v2_test_primary.json      the Test primary comparison (unsealed, recorded)
  results/v2/v2_culver_primary.json    the Culver primary comparison
  results/baselines/where2comm_v2/scored_v2/summary_deterministic.{csv,json}
  results/manifests/V2_PRIMARY_FREEZE.json   the frozen selector and comparator

    python tools/build_v2_paper_numbers.py [--check]
"""
from __future__ import annotations
import argparse, hashlib, json, os, sys
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, 'paper', 'v2_draft', 'tables', 'generated_numbers.tex')
W2C = os.path.join(ROOT, 'results/baselines/where2comm_v2/scored_v2')


def sha(p):
    return hashlib.sha256(open(p, 'rb').read()).hexdigest()


def build():
    t = json.load(open(os.path.join(ROOT, 'results/v2/v2_test_primary.json')))
    c = json.load(open(os.path.join(ROOT, 'results/v2/v2_culver_primary.json')))
    fr = json.load(open(os.path.join(ROOT, 'results/manifests/V2_PRIMARY_FREEZE.json')))
    w = pd.read_csv(os.path.join(W2C, 'summary_deterministic.csv'))
    L = [r'% GENERATED by tools/build_v2_paper_numbers.py -- do not edit by hand (V2-R42 B-2).',
         r'% Every figure below traces to a closed-out product; see the publication manifest.']

    # Greek-letter macro names collide with LaTeX built-ins (\Delta, \Lambda, \Tau), so every
    # macro is emitted with \providecommand plus \renewcommand rather than \newcommand: a name
    # clash then fails loudly at generation review rather than at compile time.
    def mac(name, val):
        assert not any(ch.isdigit() for ch in name), name
        L.append(r'\newcommand{\%s}{%s}' % (name, val))

    for tag, d in (('Test', t), ('Culver', c)):
        mac(f'{tag}RFFone', f"{d['RF']['scene_equal_f1']:.5f}")
        mac(f'{tag}TauFone', f"{d['tau']['scene_equal_f1']:.5f}")
        mac(f'{tag}RFPay', f"{d['RF']['mean_payload']:.5f}")
        mac(f'{tag}TauPay', f"{d['tau']['mean_payload']:.5f}")
        mac(f'{tag}DeltaFone', f"{d['delta_f1_point']:+.5f}")
        mac(f'{tag}LCB', f"{d['delta_f1_LCB95']:+.5f}")
        mac(f'{tag}UCBPay', f"{d['delta_payload_UCB95']:+.5f}")
        mac(f'{tag}Saving', f"{d['relative_payload_saving'] * 100:.2f}")
        mac(f'{tag}Scenes', str(d['n_scenes']))
        mac(f'{tag}Rows', f"{d['n_rows']:,}")
        mac(f'{tag}NoCollab', f"{d['dual_accounting']['no_collaborator_share'] * 100:.2f}")
        mac(f'{tag}RhoE', f"{d['action_mix']['E']:.3f}")
        mac(f'{tag}RhoL', f"{d['action_mix']['L']:.3f}")
        mac(f'{tag}RhoF', f"{d['action_mix']['F']:.3f}")
        # the shortfall on the BOUND -- the quantity C-1 requires beside every saving
        mac(f'{tag}Shortfall', f"{abs(d['delta_f1_LCB95']) - t['delta']:.4f}")
        # B-1 review: "two orders of magnitude" was wrong -- the ratio is emitted so the prose
        # cannot drift from it.
        mac(f'{tag}Ratio', f"{d['tau']['mean_payload'] / d['RF']['mean_payload']:.0f}")
        for a in ('E', 'L', 'F'):
            mac(f'{tag}Rho{a}Pct', f"{d['action_mix'][a] * 100:.1f}")
    mac('DeltaMargin', f"{t['delta']:.3f}")
    mac('TauStar', f"{fr['primary_comparator']['tau']}")
    mac('CandIdx', str(fr['selector']['candidate_index']))
    mac('LambdaStar', str(fr['selector']['lambda']))
    for tag, sp in (('Test', 'test'), ('Culver', 'culver')):
        r = w[(w.split == sp) & (w.threshold == 0.02)].iloc[0]
        mac(f'WtwoC{tag}APfifty', f"{r.ap_50:.5f}")
        mac(f'WtwoC{tag}APseventy', f"{r.ap_70:.5f}")
        mac(f'WtwoC{tag}Rate', f"{r.comm_rate * 100:.1f}")
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    return '\n'.join(L) + '\n'


def main():
    ap = argparse.ArgumentParser(); ap.add_argument('--check', action='store_true')
    a = ap.parse_args()
    body = build()
    if a.check:
        if not os.path.exists(OUT):
            print('V2 PAPER NUMBERS FAIL: not generated'); return 1
        cur = open(OUT).read()
        if cur != body:
            print('V2 PAPER NUMBERS FAIL: the committed macros are not what the generator writes '
                  '-- re-run tools/build_v2_paper_numbers.py')
            return 1
        print(f'v2 paper numbers: {body.count(chr(92) + "newcommand")} macros, byte-reproduced')
        return 0
    open(OUT, 'w').write(body)
    print(f'wrote {os.path.relpath(OUT, ROOT)}  ({body.count(chr(92) + "newcommand")} macros)')
    return 0


if __name__ == '__main__':
    sys.exit(main())
