#!/usr/bin/env python3
# -*- coding: utf-8 -*-
r"""R46-4: gate counts are computed from the registry, never typed.

A count that is typed is a count that goes stale. This reads `verify_results.GATES` -- plus the one
gate the runner executes inline -- and writes every number, in every file that states one.

R70 finished the job. The tool governed four sites and **six more were still hand-written** (4 + 6 = the ten listed below), three
of them wrong at the same moment: `README.md` said "all 11 gates (--content-only = the 7 a clean
clone can run)" when the answer was 21 and 13, and two files said "the two artefact-tier gates" when
there were eight. That was the fifth time a hand-written gate count went stale (R46-4, R47-5,
R67 c, R68, R70). There is now no hand-written gate-count site left in the live tree.

GOVERNED SITES -- ten, across five files:

    docs/reproducibility.md   the GATE-COUNTS block (tier 1 / tier 2)
                              "N gate results" in the six-step table
                              "All N checks run and pass on the full experiment machine."
                              "All N content-tier checks run on the committed tree"
    tools/verify_results.py   the usage line "(N of M)"
                              the GATE-COUNT-LINE
                              "the <word> artefact-tier gates fail loudly"
    docs/installation.md      "its <word> artefact-tier gates fail loudly"
    README.md                 "all N gates (--content-only = the M a clean clone can run)"
    docs/experiment_protocol.md  "**N checks, all passing**" in Current authoritative state

EVERY PATTERN MUST MATCH EXACTLY ONCE. A reworded sentence that stops matching is a FAIL here, not a
silent no-op -- the R43-4 lesson, applied to this tool: a generator that quietly writes nothing is
worse than one that is missing.

R71 correction, worth keeping where it happened: this docstring said "five more" and the constant
below said "five more sites", after a sixth had been added in the same batch. **The tool that exists
to stop hand-written counts going stale had a hand-written count of its own, and it was wrong within
minutes of being written.** A count in a comment is exactly as untrustworthy as a count in prose;
the difference is only that no gate reads a comment. The rule this file already applies to the
delivered text applies to itself: if it can be generated, generate it -- and if it cannot, expect it
to be wrong and keep it out of anything a reader has to rely on. The authoritative list is GOVERNED,
which the code builds; the prose above is commentary and is checked by reading, not by running.

`--check` fails when any governed file differs from what the registry produces.
`--self-test` proves each site is really governed by perturbing it and requiring the check to fire.

    python tools/build_gate_counts.py [--check] [--self-test]
"""
from __future__ import annotations

import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, 'tools'))

REPRO = os.path.join(ROOT, 'docs', 'reproducibility.md')
VERIFY = os.path.join(ROOT, 'tools', 'verify_results.py')
INSTALL = os.path.join(ROOT, 'docs', 'installation.md')
README = os.path.join(ROOT, 'README.md')
PROTOCOL = os.path.join(ROOT, 'docs', 'experiment_protocol.md')
WORDS = {1: 'one', 2: 'two', 3: 'three', 4: 'four', 5: 'five', 6: 'six', 7: 'seven', 8: 'eight',
         9: 'nine', 10: 'ten', 11: 'eleven', 12: 'twelve', 13: 'thirteen', 14: 'fourteen',
         15: 'fifteen', 16: 'sixteen', 17: 'seventeen', 18: 'eighteen', 19: 'nineteen',
         20: 'twenty', 21: 'twenty-one', 22: 'twenty-two', 23: 'twenty-three'}


def word(n):
    """Spelled-out form for the artefact-tier count. Falls back to digits rather than guessing:
    a wrong word is worse than a digit, and the suite is not going to reach 24 gates quietly."""
    return WORDS.get(n, str(n))
BEGIN = '<!-- GATE-COUNTS:BEGIN (generated by tools/build_gate_counts.py -- do not edit) -->'
END = '<!-- GATE-COUNTS:END -->'
USAGE_RX = re.compile(r'(only the checks a CLEAN CLONE can run \()\d+ of \d+(\))')
# R47-5: a fourth hand-written count ("Nine checks: the five original gates ...") had been stale
# since the suite passed nine. Same root cause, same fix: the line is generated from the runner.
COUNT_LINE_RX = re.compile(r'  GATE-COUNT-LINE: \d+ checks in total, \d+ of which a clean clone '
                           r'can run\.')
# R70: six more sites, each previously hand-written -- five found by sweeping the live tree,
# and the sixth (PROTOCOL_RX) by sweeping R70's own work afterwards.
FULL_RUN_RX = re.compile(r'All \*\*\d+\*\* checks run and pass on the full experiment machine[^.]*\.')
CONTENT_TIER_RX = re.compile(r'All \d+ content-tier checks run on the committed tree')
ARTEFACT_RX = re.compile(r'the [a-z-]+ artefact-tier gates fail loudly')
INSTALL_RX = re.compile(r'its [a-z-]+ artefact-tier gates fail loudly')
README_RX = re.compile(r'# all \d+ gates \(--content-only = the \d+ a clean clone can run\)')
# the protocol's "Current authoritative state" row (R69-3) stated the count by hand from the day it
# was written -- the tenth site, found by R70's own sweep of its own work.
PROTOCOL_RX = re.compile(r'\*\*\d+ checks, all passing\*\*')


def counts():
    """(total, content-tier names) as the runner ACTUALLY runs them.

    `GATES` is not the whole registry: `stale-fingerprint exit` is run inline by `__main__` and
    printed like the rest, so counting `len(GATES)` gives 17 while the suite reports 18. Counting
    the list and not the runner is how the hand-written numbers went wrong in the first place, so
    the inline gate is added explicitly here and named, not assumed.
    """
    import verify_results as v
    names = [(tier, name) for tier, name, _cmd in v.GATES]
    names.append(('content', 'stale-fingerprint exit'))     # run inline by verify_results.__main__
    content = [n for tier, n in names if tier == 'content']
    return len(names), content


def block():
    total, content = counts()
    names = ', '.join(f'`{n}`' for n in content)
    return (f'{BEGIN}\n'
            f'* **Tier 1 --- committed-content consistency**: `python tools/verify_results.py '
            f'--content-only` runs **{len(content)} of the {total}** gates ({names}); the other '
            f'**{total - len(content)} are skipped and reported as skipped**. No dataset, no GPU, no '
            f'OpenCOOD checkout. What this tier can establish is bounded and worth stating plainly: '
            f'**the committed results are internally consistent, and the documents still say what '
            f'those results say.** It cannot establish that the results are reproducible from raw '
            f'data.\n'
            f'* **Tier 2 --- full run**: `python tools/verify_results.py` runs all **{total}**. '
            f'Additionally requires the sibling `../OpenCOOD/` checkout, the local grids '
            f'`data/p2/p2_grid_*.csv` and the frozen models `data/p2/selector_B0*.pkl`. '
            f'**Independent reproduction from the raw OPV2V data needs all three, and none of them '
            f'is in this repository** --- so a third party can verify the internal chain here and '
            f'must obtain the dataset and re-run steps 1--4 to verify the rest.\n'
            f'{END}')


def step6_line():
    total, _ = counts()
    return f'{total} gate results'


def sub_once(text, rx, repl, what):
    """Substitute exactly once. Zero matches is a FAIL, not a no-op: a sentence reworded out of
    this tool's reach becomes a hand-written count again, silently. (R43-4, applied here.)"""
    out, n = rx.subn(repl, text)
    if n != 1:
        raise SystemExit(f'build_gate_counts: {what} matched {n} time(s), expected exactly 1 -- '
                         'the sentence was reworded and is no longer governed. Fix the pattern or '
                         'restore the sentence; do not leave the count hand-written.')
    return out


def render(text):
    total, content = counts()
    artefact = total - len(content)
    i, j = text.find(BEGIN), text.find(END)
    if i < 0 or j < 0:
        raise SystemExit('build_gate_counts: the GATE-COUNTS markers are missing from '
                         'docs/reproducibility.md')
    out = text[:i] + block() + text[j + len(END):]
    # the six-step table's last row also carries the count
    out = sub_once(out, re.compile(r'\d+ gate results'), step6_line(), 'the six-step table row')
    out = sub_once(out, FULL_RUN_RX,
                   f'All **{total}** checks run and pass on the full experiment machine.',
                   'the full-run status sentence')
    out = sub_once(out, CONTENT_TIER_RX,
                   f'All {len(content)} content-tier checks run on the committed tree',
                   'the content-tier sentence')
    return out


def render_verify(text):
    total, content = counts()
    out = sub_once(text, USAGE_RX, lambda m: f'{m.group(1)}{len(content)} of {total}{m.group(2)}',
                   'the usage line')
    out = sub_once(out, COUNT_LINE_RX,
                   f'  GATE-COUNT-LINE: {total} checks in total, '
                   f'{len(content)} of which a clean clone can run.', 'the GATE-COUNT-LINE')
    out = sub_once(out, ARTEFACT_RX,
                   f'the {word(total - len(content))} artefact-tier gates fail loudly',
                   'the artefact-tier sentence in verify_results.py')
    return out


def render_install(text):
    total, content = counts()
    return sub_once(text, INSTALL_RX,
                    f'its {word(total - len(content))} artefact-tier gates fail loudly',
                    'the artefact-tier sentence in installation.md')


def render_readme(text):
    total, content = counts()
    return sub_once(text, README_RX,
                    f'# all {total} gates (--content-only = the {len(content)} a clean clone can run)',
                    'the README command comment')


def render_protocol(text):
    total, _ = counts()
    return sub_once(text, PROTOCOL_RX, f'**{total} checks, all passing**',
                    "the protocol's Current-authoritative-state row")


GOVERNED = ((REPRO, render), (VERIFY, render_verify), (INSTALL, render_install),
            (README, render_readme), (PROTOCOL, render_protocol))


def self_test():
    """Perturb each governed site and require --check to report that file stale."""
    total, content = counts()
    print(f'registry: {total} checks, {len(content)} content-tier, '
          f'{total - len(content)} artefact-tier ({word(total - len(content))})')
    ok = True
    for path, render_fn in GOVERNED:
        rel = os.path.relpath(path, ROOT)
        cur = open(path, encoding='utf-8').read()
        clean = (render_fn(cur) == cur)
        # A wrong count anywhere in the file must make the render disagree with what is on disk.
        # Perturb BOTH forms: installation.md states its count as a WORD ("eight"), so a
        # digits-only perturbation left it untouched and the site reported DOES NOT FIRE -- i.e.
        # the self-test was not actually testing that file.
        broken = re.sub(r'\b(\d+)\b', lambda m: str(int(m.group(1)) + 7), cur, count=0)
        broken = re.sub(r'\b(' + '|'.join(WORDS.values()) + r')\b(?= artefact-tier gates)',
                        'nineteen', broken)
        try:
            fires = (render_fn(broken) != broken)
        except SystemExit:
            fires = True                      # pattern no longer matches -> also a failure, correctly
        print(f'  {rel:28} current==generated: {"OK" if clean else "STALE"}   '
              f'perturbed -> {"FIRES" if fires else "DOES NOT FIRE"}')
        ok &= clean and fires
    # and a reworded sentence must FAIL rather than silently write nothing
    reworded = open(README, encoding='utf-8').read().replace(
        '# all', '# ALL-REWORDED', 1)
    try:
        render_readme(reworded)
        silent = True
    except SystemExit:
        silent = False
    print(f'  reworded sentence -> {"FAILS loudly" if not silent else "SILENT NO-OP (bad)"}')
    ok &= not silent
    print('SELF-TEST ' + ('PASS' if ok else 'FAIL'))
    return 0 if ok else 1


def main() -> int:
    if '--self-test' in sys.argv:
        return self_test()
    check = '--check' in sys.argv
    total, content = counts()
    current = {p: open(p, encoding='utf-8').read() for p, _fn in GOVERNED}
    wanted = {p: fn(current[p]) for p, fn in GOVERNED}
    if check:
        stale = [p for p in current if current[p] != wanted[p]]
        if stale:
            print('GATE COUNT CHECK FAIL: ' + ', '.join(os.path.relpath(p, ROOT) for p in stale)
                  + f' disagree(s) with the registry ({len(content)} content of {total} total, '
                    f'{total - len(content)} artefact-tier)'
                    ' -- re-run: python tools/build_gate_counts.py')
            return 1
        print(f'GATE COUNT CHECK PASS: {len(content)} content-tier of {total} gates '
              f'({total - len(content)} artefact-tier), stated the same in all '
              f'{len(GOVERNED)} governed files.')
        return 0
    for p in current:
        open(p, 'w', encoding='utf-8').write(wanted[p])
    print(f'wrote the gate counts ({len(content)} content-tier of {total} total, '
          f'{total - len(content)} artefact-tier) across {len(GOVERNED)} files')
    return 0


if __name__ == '__main__':
    sys.exit(main())
